dnanexus/dxWDL

src/main/scala/dxWDL/WdlPrettyPrinter.scala

The WDL spec says you can put `meta` and `parameter_meta` blocks in a `workflow`. But the WdlPrettyPrinter currently strips the quotes from the value. Then wdl4s is unhappy.
Here is a test WDL that this fixes:
```
task CountLines {
File input_file
command <<<
wc -l ${input_file} | awk '{print $1}' > line.count
>>>
output {
Int line_count = read_int("line.count")
}
}
workflow CountLinesWorkflow {
File input_file
call CountLines {
input: input_file=input_file
}
output {
Int line_count=CountLines.line_count
}
parameter_meta {
input_file: "a file that is input"
}
meta {
this: "is allowed"
even_some: "emoji should work  🌕 🌖 🌗 🌘 🌑 🌒 🌓 🌔"
}
}
```

Quote workflow-level meta and parameter_meta values

---

src/main/scala/dxWDL/InstanceTypeDB.scala

I think SDD might have been a typo? At a minimum, it's somewhat intuitive that you'd say `local-disk 1000 SSD` in a runtime block :)

Allow SSD in disk specification.

---

RELEASE_NOTES.md
scripts/compiler_image/dxwdl

Really excited about new docker changes! Took a quick glance and a had a small suggestion about dxwdl script.
- Version [docker-based runner script](https://github.com/dnanexus/dxWDL/blob/master/scripts/compiler_image/runc.sh)
- Do not call sudo in runner script, in case system is set up not to require
sudo to run Docker.
- Rename run script to `dxwdl` for elegance
```
$ export DXWDL_VERSION=0.79.1
$ sudo dxwdl.sh compile /path/to/foo.wdl -project project-xxx
```

Allow version to be specified in docker script

---

README.md

The output section has to have full definitions. This has been documented at the beginning of the README.md file.

Documentation for output section limitation

---

contrib/docker/Dockerfile

update dx-toolkit to 0.275 which supports private docker repos

update dx-toolkit version

---

src/main/scala/dxWDL/dx/DxFindDataObjects.scala

I noticed that lookups for workflows and applets in the current folder seemed to have too high of a count (as if they were grabbing everything in the archive too). From findDataObjects API docs:
```
recurse boolean (optional, default true) Whether the search should be performed recursively on subfolders as well
```
So we need to set `recurse` explicitly to `false` to use API correctly and have results return back faster.
I think this should help quite a bit for workflows, where we've been seeing 16-30s look up times when someone reuses the same path over and over :)

FindDataObjects: Correctly represent recurse == false

---

scripts/run_tests.py
src/main/resources/application.conf
src/main/scala/dxWDL/exec/JobInputOutput.scala
src/test/resources/compiler/streaming_files_obj.wdl
src/test/scala/dxWDL/compiler/GenerateIRTest.scala
test/wdl_1_0/streaming_inputs.wdl
test/wdl_1_0/streaming_inputs_input.json
test/wdl_1_0/streaming_inputs_output.json

Add support for recognizing the "stream" annotation in an object value of a parameter_meta key:
```
parameter_meta {
foo: {
stream: true
}
}
```

Support object form of 'stream' annotation in parameter_meta

---

src/main/scala/dxWDL/Main.scala

Added check for if reorg is provided in extras.json and -locked in provided for the dxWDL workflow compile command. If it is then throw an InvalidInputException, otherwise proceed.

Check if -locked supplied with reorg field in extras.json 

---

src/main/java/com/dnanexus/DXHTTPRequest.java

Hi, @orodeh  as discussed, I have commented out all logError in src/main/java/com/dnanexus/DXHTTPRequest.java
I have also checked that the message is no longer in the stdout.
I think another way is to modify the logError method to check the environment variable `_DX_DEBUG` do you think that will work? Although that will introduce another variable that we have to be aware of
ie something like
```
private static void logError(String msg) {
System.err.println("[" + System.currentTimeMillis() + "] " + msg);
}
```
to 
```
private static void logError(String msg) {
if (System.getenv("_DX_DEBUG") != null) {
System.err.println("[" + System.currentTimeMillis() + "] " + msg);
}
}
```

Silencer added to DXHTTRequest

---

RELEASE_NOTES.md
doc/ExpertOptions.md
src/main/scala/dxWDL/compiler/GenerateIRTask.scala
src/main/scala/dxWDL/compiler/IR.scala
src/main/scala/dxWDL/compiler/Native.scala
src/main/scala/dxWDL/dx/package.scala
src/test/resources/compiler/pattern_obj_params.wdl
src/test/scala/dxWDL/compiler/GenerateIRTest.scala
src/test/scala/dxWDL/compiler/NativeTest.scala

This is a PR to add the object value to the parameter_meta.patterns field. So it now is feature complete with what is described in this document: https://documentation.dnanexus.com/developer/api/running-analyses/io-and-run-specifications.
Example
```
version 1.0
task pattern_params_obj_cgrep {
input {
String pattern
File in_file
}
parameter_meta {
in_file: {
help: "The input file to be searched",
patterns: {
name: ["*.txt", "*.tsv"],
class: "file",
tag: ["foo", "bar"]
}
}
pattern: {
help: "The pattern to use to search in_file"
}
out_file: {
patterns: ["*.txt", "*.tsv"]
}
}
command {
grep '${pattern}' ${in_file} | wc -l
cp ${in_file} out_file
}
output {
Int count = read_int(stdout())
File out_file = "out_file"
}
}
```

Patterns object

---

scripts/proxy_test.py
scripts/run_tests.py
src/main/scala/dxWDL/compiler/Native.scala

There was a wrong comparison when looking for other versions of the same applet. It is weird that scala type safety did not flag this, because two different types were compared. They could never match.

Error: bad object DxApplet during workflow compilation with -projectWideReuse option

---

RELEASE_NOTES.md
doc/ExpertOptions.md
src/main/scala/dxWDL/compiler/GenerateIRTask.scala
src/main/scala/dxWDL/compiler/IR.scala
src/main/scala/dxWDL/compiler/Native.scala
src/main/scala/dxWDL/dx/package.scala
src/test/resources/compiler/add_default.wdl
src/test/resources/compiler/add_dx_type.wdl
src/test/resources/compiler/add_help.wdl
src/test/resources/compiler/default_type_mismatch.wdl
src/test/resources/compiler/dx_type_nonfile.wdl
src/test/resources/compiler/help_input_params.wdl
src/test/scala/dxWDL/compiler/GenerateIRTest.scala
src/test/scala/dxWDL/compiler/NativeTest.scala

This PR is the last set of enhancements for DEVEX-1473. It is now possible to specify all of the keywords in the dxapp inputSpec directly in WDL parameter_meta (with a few limitations that are described in the docs).
* dx_type maps to 'type' in dxapp inputSpec
* description can be used as an alias for help (but 'help' takes precedence)
* default can be used to specify the default value for an optional parameter
* parameter_meta is now parsed for optional parameters
I also reformatted some files with scalafmt.

Add support for 'dx_type' and 'description' parameter_meta

---

doc/ExpertOptions.md
src/main/scala/dxWDL/base/Utils.scala
src/main/scala/dxWDL/compiler/GenerateIR.scala
src/main/scala/dxWDL/compiler/GenerateIRTask.scala
src/main/scala/dxWDL/compiler/GenerateIRWorkflow.scala
src/main/scala/dxWDL/compiler/IR.scala
src/main/scala/dxWDL/compiler/Top.scala
src/main/scala/dxWDL/compiler/WdlCodeGen.scala
src/main/scala/dxWDL/util/Adjunct.scala
src/main/scala/dxWDL/util/ParseWomSourceFile.scala
src/test/resources/compiler/Readme.wf_readme.add.md
src/test/resources/compiler/Readme.wf_readme.wf_linear.md
src/test/resources/compiler/wf_readme.wdl
src/test/scala/dxWDL/compiler/GenerateIRTest.scala
src/test/scala/dxWDL/exec/TaskRunnerTest.scala
src/test/scala/dxWDL/exec/WfFragRunnerTest.scala
src/test/scala/dxWDL/util/BlockTest.scala

This PR introduces the concept of "adjunct" files, which are files in the same directory as the WDL that provide additional information.
Currently, there are two types of adjunct files:
* Readme: must have name `Readme.<wdlname>.<taskname>.md`, where wdlname is the name of the WDL file without the ".wdl" extension, and taskname is the name of the task. Filenames are matched case-insensitively.
* Developer Notes: must have name `Readme.developer.<wdlname>.<taskname>.md`
During parsing, adjunct files are discovered by name. During conversion to IR, if the task metadata does not have "description" and there was a Readme adjunct discovered, the description is set to the contents of that file. Similarly, if developer_notes is not defined in the applet meadata and Developer Notes adjunct was …

Load app description and developer notes from readme files

---

doc/ExpertOptions.md
src/main/scala/dxWDL/base/Extras.scala
src/main/scala/dxWDL/compiler/GenerateIRTask.scala
src/main/scala/dxWDL/compiler/IR.scala
src/main/scala/dxWDL/compiler/Native.scala
src/main/scala/dxWDL/compiler/WdlCodeGen.scala
src/main/scala/dxWDL/dx/DxApplet.scala
src/main/scala/dxWDL/dx/package.scala
src/main/scala/dxWDL/exec/JobInputOutput.scala
src/main/scala/dxWDL/util/Adjunct.scala
src/test/resources/compiler/add_runtime_hints.wdl
src/test/resources/compiler/extras/task_specific_short_timeout.json
src/test/scala/dxWDL/compiler/GenerateIRTest.scala
src/test/scala/dxWDL/compiler/NativeTest.scala

This PR adds four runtime hints:
* executionPolicy (which is specified in WDL task runtime using the `dx_restart` key)
* timeoutPolicy (which is specified in WDL task runtime using the `dx_timeout` key)
* access (which is specified in WDL task runtime using the `dx_access` key)
* ignoreReuse  (which is specified in WDL task runtime using the `dx_ignore_reuse` key)

Add support for runtime hints

---

RELEASE_NOTES.md
src/main/resources/application.conf
src/main/scala/dxWDL/util/InstanceTypeDB.scala

Exclude AWS nano instances from those that can run WDL auxiliary calculations. For example, expression evaluation, or scatter launch/collect.

Exclude nano instances

---

src/main/scala/dx/compiler/GenerateIRWorkflow.scala
src/main/scala/dx/compiler/Main.scala
src/main/scala/dx/core/languages/wdl/Block.scala

When creating the closure for an output section, it appears that for references to structs, only the struct name, not the specific member accessed, gets added to the environment. So we have to add a special case when constructing the closure.
Note that this may in fact be a bug with how we build the environment, not the closure. We should make a note of this in case any more bugs of this nature crop up.

Special handling for structs when creating output closures

---

src/main/scala/dxWDL/compiler/DxNI.scala
src/main/scala/dxWDL/dx/DxFile.scala
src/main/scala/dxWDL/dx/DxFindDataObjects.scala
src/main/scala/dxWDL/exec/TaskRunner.scala
src/main/scala/dxWDL/util/Block.scala
src/main/scala/dxWDL/util/InstanceTypeDB.scala
src/main/scala/dxWDL/util/ParseWomSourceFile.scala
src/test/scala/dxWDL/compiler/NativeTest.scala
src/test/scala/dxWDL/dx/DxdaManifestTest.scala
src/test/scala/dxWDL/exec/TaskRunnerTest.scala
src/test/scala/dxWDL/util/InstanceTypeDBTest.scala

TaskRunner fails if `RepoTags` is missing or has a null value in the manifest of the docker tarball. However, `docker load` prints out the repo name. This change uses the results of `docker load` if the attempt to read the repo if reading from the manifest fails.
There's also some code reformatting here due to my scalafmt git hook. The only real changes are in TaskRunner and TaskRunnerTest.

Handle null repo

---

src/main/scala/dx/compiler/Top.scala

First, a pattern match of the form
```scala
cResults.primaryCallable match {
case Some(wf) if execTree.isDefined =>
cResults.primaryCallable match { // this is a redundant pattern match
case None =>
// dead code
case Some(primary) => // we already know that primary = wf
SOME_CODE(primary)
```
is simplified to
```scala
cResults.primaryCallable match {
case Some(wf) if execTree.isDefined =>
val primary = wf
SOME_CODE(primary)
```
Subsequently, code of the form
```scala
case Some(wf) if execTree.isDefined =>
val y = SOME_CODE(execTree.get) // Safe get because we check isDefined above
(x, Some(y))
case Some(wf) =>
(x, None)
```
is simplified to
```scala
case Some(wf) =>
val yOpt = execTree.map(SOME_CODE)
(x, yOpt)
```
which also avoids the use of the unsafe `Option#get` method.
The change is …

Simplify a pattern match in Top.scala

---

RELEASE_NOTES.md
project/plugins.sbt
src/main/resources/application.conf
src/main/scala/dxWDL/Main.scala
src/main/scala/dxWDL/base/Utils.scala
src/main/scala/dxWDL/base/package.scala
src/main/scala/dxWDL/compiler/Native.scala
src/main/scala/dxWDL/compiler/Top.scala
src/main/scala/dxWDL/dx/DxJob.scala
src/main/scala/dxWDL/dx/DxUtils.scala
src/main/scala/dxWDL/dx/package.scala
src/main/scala/dxWDL/exec/ScatterSubJobs.scala
src/main/scala/dxWDL/exec/WfFragRunner.scala
test/wdl_1_0/large_scatter.wdl

This is a change to the runtime for scatter jobs. Instead of launching all subjobs at once, only a maximum of N subjobs (where N defaults to 500 but is user configurable between 1-1000) are launched at once. When one chunk finishes, the next launches, and so on until all sub-jobs have been executed.

Break up large scatters

---

src/main/scala/dx/api/DxFindDataObjects.scala
src/main/scala/dx/compiler/DxObjectDirectory.scala
src/test/scala/dx/compiler/NativeTest.scala

In DxFindDataObjects, if a set of object names is specified, the query includes a regular expression search. The regular expression is incorrect. For example, if there are a set of app/workflow names {"foo", "bar", "baz"}, the code in dxWDL builds a regular expression to match any of them:
```[(foo)|(bar)|(baz)]```
which will match any of the characters f, o, b, a, r, z
When searching for objects in a folder with existing objects, the query takes extremely long to run. Most of the time the user thinks the program has hung and gives up (e.g. https://jira.internal.dnanexus.com/browse/APPS-140).
The correct regexp is ```^foo$|^bar$|^baz$```
This needs to be fixed in both 1.x and master.

Fix name regexp in DxFindDataObjects

---

build.sbt
src/main/resources/application.conf
src/main/scala/dx/core/languages/wdl/Block.scala
src/main/scala/dx/core/languages/wdl/ParseSource.scala
src/test/scala/dx/core/languages/wdl/WdlVarLinksTest.scala

The bug APPS-186 was due to the fact that two apps are compared as strings. If the same app is imported from two different WDL files, the parent FileSources will have different `value`s, but the same `localPath`. In wdlTools 0.6.1 the `toString` method of `LocalFileSource` is changed to use `localPath` rather than `value`, so the two applications now have identical string values again.

upgrade to wdlTools 0.6.1
