doc/WdlRunnerApp.md
A document with a rough sketch for how to write a workflow fragment runner as an app. Today, a workflow is compiled into a bunch of custom applets.
=> Description of an app based fragment runner

doc/MissingCallArguments.md, doc/WdlRunnerApp.md
Adding a document that describes the issues around missing call arguments. Also, improving the document on the app-based WDL runner.
=> Documentation improvements

README.md, doc/ExpertOptions.md, ref.conf, src/main/scala/dxWDL/compiler/DxNI.scala
* Bumping release version
* Improving error reporting for DxNI
* Updating documentation to note that the `--project` command line argument is now required
=> Minor changes

contrib/docker/Dockerfile
@orodeh - very tiny tweak
Previously always was pointing to 0.78 :(
=> Fix URL with DXWDL_VERSION arg

RELEASE_NOTES.md, doc/ExpertOptions.md, scripts/run_tests.py, src/main/resources/application.conf, src/main/scala/dxWDL/Extras.scala, src/main/scala/dxWDL/compiler/GenerateIR.scala, src/main/scala/dxWDL/compiler/Native.scala, src/test/scala/dxWDL/ExtrasTest.scala, src/test/scala/dxWDL/compiler/CompilerUnitTest.scala, test/extras.json
Allow specifying dx attributes for specific task.
=> Per task dx attributes

RELEASE_NOTES.md, build.sbt, doc/ExpertOptions.md, scripts/run_tests.py, src/main/scala/dxWDL/Main.scala, src/main/scala/dxWDL/compiler/Native.scala, src/main/scala/dxWDL/util/Block.scala, src/main/scala/dxWDL/util/DxPathConfig.scala, src/test/resources/util/empty_workflow.wdl, src/test/scala/dxWDL/compiler/GenerateIRTest.scala, src/test/scala/dxWDL/util/BlockTest.scala, src/test/scala/dxWDL/util/UtilsTest.scala, test/subworkflows/inner.wdl, test/subworkflows/outer.wdl
Upgrade to Cromwell v40
Fix CI error
Fix bug having to do with a workflow that has an empty body
Setting the womSourceCode properly
=> Cromwell v40

RELEASE_NOTES.md, src/main/scala/dxWDL/compiler/GenerateIRWorkflow.scala, src/main/scala/dxWDL/util/Block.scala, src/test/resources/util/inputs_used_as_outputs.wdl, src/test/scala/dxWDL/util/BlockTest.scala, test/subworkflows/inner.wdl, test/subworkflows/inner_input.json, test/subworkflows/inner_results.json, test/subworkflows/outer.wdl, test/subworkflows/outer_input.json, test/subworkflows/outer_results.json
Fix for issues: https://github.com/dnanexus/dxWDL/issues/225, and https://github.com/dnanexus/dxWDL/issues/224
=> Incorrect applet compilation

build.sbt, src/main/scala/dxWDL/Main.scala, src/main/scala/dxWDL/base/WomTypeSerialization.scala, src/main/scala/dxWDL/base/WomValueSerialization.scala, src/main/scala/dxWDL/util/InstanceTypeDB.scala, src/main/scala/dxWDL/util/Utils.scala, src/main/scala/dxWDL/util/package.scala, src/test/scala/dxWDL/base/WomPrettyPrintApproxWdlTest.scala, src/test/scala/dxWDL/base/WomTypeSerializationTest.scala, src/test/scala/dxWDL/base/WomValueSerializationTest.scala, src/test/scala/dxWDL/util/InstanceTypeDBTest.scala, test/docker/biocontainers.wdl
Improving code coverage, and accepting memory specifications such as "120GB".
=> Code coverage

build.sbt, src/main/resources/application.conf, src/main/scala/dxWDL/Main.scala, src/main/scala/dxWDL/base/Utils.scala, src/main/scala/dxWDL/compiler/DxObjectDirectory.scala, src/main/scala/dxWDL/compiler/GenerateIR.scala, src/main/scala/dxWDL/compiler/GenerateIRTask.scala, src/main/scala/dxWDL/compiler/GenerateIRWorkflow.scala, src/main/scala/dxWDL/compiler/Native.scala, src/main/scala/dxWDL/compiler/Top.scala, src/main/scala/dxWDL/compiler/WdlCodeGen.scala, src/main/scala/dxWDL/dx/package.scala, src/main/scala/dxWDL/exec/WfFragRunner.scala, src/main/scala/dxWDL/util/Block.scala, src/main/scala/dxWDL/util/ParseWomSourceFile.scala, src/test/resources/compiler/library.wdl, src/test/resources/compiler/wf_to_flatten.wdl, src/test/scala/dxWDL/base/UtilsTest.scala, src/test/scala/dxWDL/compiler/GenerateIRTest.scala, src/test/scala/dxWDL/compiler/NativeTest.scala, src/test/scala/dxWDL/compiler/SortTypeAliasesTest.scala, src/test/scala/dxWDL/exec/TaskRunnerTest.scala, src/test/scala/dxWDL/exec/WfFragRunnerTest.scala, src/test/scala/dxWDL/util/BlockTest.scala, src/test/scala/dxWDL/util/ParseWomSourceFileTest.scala, src/test/scala/dxWDL/util/WomPrettyPrintApproxWdlTest.scala, src/test/scala/dxWDL/util/WomValueAnalysisTest.scala
Fixes so that that the Broad Five dollar genome workflow will work.
=> Broad pipeline

src/main/scala/dxWDL/util/WdlVarLinks.scala, test/struct/type_mismatch.wdl, test/struct/type_mismatch_input.json
Improving error messages for asserts at runtime.
=> Better message for assert

scripts/run_tests.py, src/main/scala/dxWDL/exec/TaskRunner.scala, src/test/scala/dxWDL/exec/TaskRunnerTest.scala, test/single_tasks/docker_retry.wdl
@orodeh I was wondering if this is a good way to let docker pull retry a few times. Also, can I check how will you recommend I should test this?
I'm thinking 
1) Create a wdl task with a docker image that does not exist. Run the task and let it fail - check the log that it did retry 5 times
or 
2) create a wdl task with a docker image that does not exists. create docker submit script. run docker submit script and let it fail and check log that it retried 5 times
=> Proposal for docker run retry.

RELEASE_NOTES.md, build.sbt, scripts/Makefile, scripts/build_release.py, scripts/compiler_image/Dockerfile, scripts/compiler_image/build_compiler_docker_image.sh, scripts/dxwdl_copy_file/README.md, scripts/dxwdl_copy_file/code.sh, scripts/dxwdl_copy_file/dxapp.json, scripts/util.py, src/main/resources/application.conf, test/bugs/intermediate_files.wdl
Using applets to copy to remote regions, instead of relying on good connectivity from the local machine.
=> Improving the release script

.gitignore, src/main/scala/dxWDL/base/Extras.scala, src/test/scala/dxWDL/base/ExtrasTest.scala
1. Added Custom reorg parameters to extras.
2. Should print warning message.
3. Should check that value is present
=> Add custom_reorg parameters to extras.

src/test/scala/dxWDL/base/ExtrasTest.scala
Change logs
1. Fixed indentation
2. Make tests quiet.
=> Make tests quiet for extras.json. ignore test that platform.

RELEASE_NOTES.md, build.sbt, scripts/run_tests.py, scripts/util.py, src/test/scala/dxWDL/compiler/NativeTest.scala
* Upgrade to Cromwell v48
* Separating user build and test directories on the platform
=> Upgrade to Cromwell v48

RELEASE_NOTES.md, src/main/scala/dxWDL/compiler/GenerateIRTask.scala, src/main/scala/dxWDL/compiler/IR.scala, src/main/scala/dxWDL/compiler/Native.scala, src/main/scala/dxWDL/dx/package.scala, src/test/scala/dxWDL/compiler/GenerateIRTest.scala, src/test/scala/dxWDL/compiler/NativeTest.scala
Scala format and documentation
=> Running scala-format

doc/faq.md
Some FAQs that would be nice to go public.
=> Frequently asked questions and their answers for dxWDL/WDL

doc/ExpertOptions.md, doc/examples/four_levels.exectree.json, doc/examples/four_levels.exectree.pretty.txt
@orodeh  adding docs for the describe exec tree functionality. Let me know its alright. Thanks!
=> Add docs on using the describe opton

project/build.properties, src/main/scala/dxWDL/util/InstanceTypeDB.scala, src/test/scala/dxWDL/base/UtilsTest.scala, src/test/scala/dxWDL/util/InstanceTypeDBTest.scala
Could not reproduce any error, I didnt find any difference between calling orgDescribe and userDescribe (even code seems to be very much the same).
do we have any data to reproduce an error?
I also changed version of SBT in order to support Java 11 (there was a bug in 1.3.0 sbt version).
=> DEVEX - 1632 - using correct billto method if org is given

src/main/scala/dxWDL/Main.scala, src/main/scala/dxWDL/base/Adjunct.scala, src/main/scala/dxWDL/base/ParseWomSourceFile.scala, src/main/scala/dxWDL/compiler/GenerateIR.scala, src/main/scala/dxWDL/compiler/GenerateIRTask.scala, src/main/scala/dxWDL/compiler/Top.scala, src/main/scala/dxWDL/util/Block.scala
Also fixed some issues suggested by IDE inspections.
This requires building from wdlTools `dxWDL` branch and publishing to local repository.
=> Fix unirary -> unary spelling (changed in latest wdlTools snapshot)

src/main/scala/dxWDL/compiler/DxNI.scala
each task is validated before being added to the DxNI document
=> Validate DxNI tasks

src/main/scala/dxWDL/Main.scala, src/main/scala/dxWDL/dx/DxJob.scala, src/main/scala/dxWDL/dx/package.scala, src/test/scala/dxWDL/base/ExtrasTest.scala, src/test/scala/dxWDL/dx/DxFileTest.scala, src/test/scala/dxWDL/dx/DxJobTest.scala
applet run: https://staging.dnanexus.com/projects/FGpfqjQ0ffPF1Q106JYP2j3v/monitor/job/Fqy8XV00ffP3b1j75bvVFX3b
app run: https://staging.dnanexus.com/projects/FGpfqjQ0ffPF1Q106JYP2j3v/monitor/job/Fqy8YF00ffPB148G5f490Y25
=> APPS-44 Make WDL apps runnable

scripts/util.py, src/main/java/com/dnanexus/DXHTTPRequest.java
* bump dxda to 0.5.4
* increase retries for API calls to 10
=> Bump dxda 1.45

scripts/util.py, src/main/java/com/dnanexus/DXHTTPRequest.java
* bump dxda version to 0.5.4
* increase API retries to 10
=> Bump dxda in v1

project/plugins.sbt, src/main/scala/dxWDL/compiler/DxNI.scala, src/main/scala/dxWDL/dx/DxFindDataObjects.scala, src/main/scala/dxWDL/dx/DxJob.scala, src/main/scala/dxWDL/exec/CollectSubJobs.scala
Add "fields" key to describe for all system/findXXX calls.
=> add 'fields' key when calling system/findXXX with describe

src/main/scala/dxWDL/compiler/DxNI.scala, src/main/scala/dxWDL/dx/DxFindDataObjects.scala, src/main/scala/dxWDL/exec/ScatterSubJobs.scala, src/test/scala/dxWDL/exec/WfFragRunnerTest.scala
Add "fields" key to describe for all system/findXXX calls.
=> Fix describe v1
